### ISSUE TITLE
matmulTN fails when the two parameters are the same array (Intel/OpenCL)

### ISSUE THREAD

**Issue by unbornchikken** [arrayfire/arrayfire#1711]
Original issue: https://github.com/arrayfire/arrayfire-python/pull/114#issuecomment-273244735

clinfo:

```
Number of platforms:				 2
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 1.2 
  Platform Name:				 Intel(R) OpenCL
  Platform Vendor:				 Intel(R) Corporation
  Platform Extensions:				 cl_intel_dx9_media_sharing cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_d3d11_sharing cl_khr_depth_images cl_khr_dx9_media_sharing cl_khr_gl_sharing cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_icd cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_spir
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.0 
  Platform Name:				 Experimental OpenCL 2.0 CPU Only Platform
  Platform Vendor:				 Intel(R) Corporation
  Platform Extensions:				 cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_spir cl_intel_exec_by_local_thread cl_khr_depth_images cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_fp64 cl_intel_dx9_media_sharing cl_khr_dx9_media_sharing cl_khr_d3d11_sharing cl_khr_gl_sharing


  Platform Name:				 Intel(R) OpenCL
Number of devices:				 2
  Device Type:					 CL_DEVICE_TYPE_GPU
  Device ID:					 32902
  Max compute units:				 20
  Max work items dimensions:			 3
    Max work items[0]:				 512
    Max work items[1]:				 512
    Max work items[2]:				 512
  Max work group size:				 512
  Preferred vector width char:			 1
  Preferred vector width short:			 1
  Preferred vector width int:			 1
  Preferred vector width long:			 1
  Preferred vector width float:			 1
  Preferred vector width double:		 0
  Max clock frequency:				 1200Mhz
  Address bits:					 14757395255531667520
  Max memory allocation:			 390280806
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 128
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 16
  Max size of kernel argument:			 1024
  Alignment (bits) of base address:		 1024
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 No
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 No
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 262144
  Global memory size:				 1561123226
  Constant buffer size:				 65536
  Max number of constant args:			 8
  Local memory type:				 Scratchpad
  Local memory size:				 65536
  Error correction support:			 0
  Profiling timer resolution:			 80
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 No
  Queue properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Platform ID:					 01020620
  Name:						 Intel(R) HD Graphics 4600
  Vendor:					 Intel(R) Corporation
  Driver version:				 20.19.15.4531
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 
  Extensions:					 cl_intel_accelerator cl_intel_advanced_motion_estimation cl_intel_ctz cl_intel_d3d11_nv12_media_sharing cl_intel_dx9_media_sharing cl_intel_motion_estimation cl_intel_simultaneous_sharing cl_intel_subgroups cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_depth_images cl_khr_dx9_media_sharing cl_khr_gl_depth_images cl_khr_gl_event cl_khr_gl_msaa_sharing cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_gl_sharing cl_khr_icd cl_khr_image2d_from_buffer cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_spir 


  Device Type:					 CL_DEVICE_TYPE_CPU
  Device ID:					 32902
  Max compute units:				 8
  Max work items dimensions:			 3
    Max work items[0]:				 8192
    Max work items[1]:				 8192
    Max work items[2]:				 8192
  Max work group size:				 8192
  Preferred vector width char:			 1
  Preferred vector width short:			 1
  Preferred vector width int:			 1
  Preferred vector width long:			 1
  Preferred vector width float:			 1
  Preferred vector width double:		 1
  Max clock frequency:				 3600Mhz
  Address bits:					 14757395255531667488
  Max memory allocation:			 536838144
  Image support:				 Yes
  Max number of images read arguments:		 480
  Max number of images write arguments:		 480
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 480
  Max size of kernel argument:			 3840
  Alignment (bits) of base address:		 1024
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 Yes
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 No
    Round to +ve and infinity:			 No
    IEEE754-2008 fused multiply-add:		 No
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 262144
  Global memory size:				 2147352576
  Constant buffer size:				 131072
  Max number of constant args:			 480
  Local memory type:				 Global
  Local memory size:				 32768
  Error correction support:			 0
  Profiling timer resolution:			 285
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 Yes
  Queue properties:				 
    Out-of-Order:				 Yes
    Profiling :					 Yes
  Platform ID:					 01020620
  Name:						 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  Vendor:					 Intel(R) Corporation
  Driver version:				 5.2.0.10094
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 (Build 10094)
  Extensions:					 cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_depth_images cl_khr_3d_image_writes cl_intel_exec_by_local_thread cl_khr_spir cl_khr_dx9_media_sharing cl_intel_dx9_media_sharing cl_khr_d3d11_sharing cl_khr_gl_sharing cl_khr_fp64 


  Platform Name:				 Experimental OpenCL 2.0 CPU Only Platform
Number of devices:				 1
  Device Type:					 CL_DEVICE_TYPE_CPU
  Device ID:					 32902
  Max compute units:				 8
  Max work items dimensions:			 3
    Max work items[0]:				 8192
    Max work items[1]:				 8192
    Max work items[2]:				 8192
  Max work group size:				 8192
  Preferred vector width char:			 1
  Preferred vector width short:			 1
  Preferred vector width int:			 1
  Preferred vector width long:			 1
  Preferred vector width float:			 1
  Preferred vector width double:		 1
  Max clock frequency:				 3600Mhz
  Address bits:					 14757395255531667488
  Max memory allocation:			 536838144
  Image support:				 Yes
  Max number of images read arguments:		 480
  Max number of images write arguments:		 480
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 480
  Max size of kernel argument:			 3840
  Alignment (bits) of base address:		 1024
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 Yes
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 No
    Round to +ve and infinity:			 No
    IEEE754-2008 fused multiply-add:		 No
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 262144
  Global memory size:				 2147352576
  Constant buffer size:				 131072
  Max number of constant args:			 480
  Local memory type:				 Global
  Local memory size:				 32768
  Error correction support:			 0
  Profiling timer resolution:			 285
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 Yes
  Queue properties:				 
    Out-of-Order:				 Yes
    Profiling :					 Yes
  Platform ID:					 01058E78
  Name:						 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  Vendor:					 Intel(R) Corporation
  Driver version:				 6.0.0.1049
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 2.0 (Build 162)
  Extensions:					 cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_spir cl_intel_exec_by_local_thread cl_khr_depth_images cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_fp64 cl_intel_dx9_media_sharing cl_khr_dx9_media_sharing cl_khr_d3d11_sharing cl_khr_gl_sharing 
```

ArrayFire Python's backend and device is the default.

Error:
```
ERROR:root:Traceback (most recent call last):
  File "C:\git\arrayfire-python\arrayfire\tests\simple\_util.py", line 32, in run
    test(verbose)
  File "C:\git\arrayfire-python\arrayfire\tests\simple\lapack.py", line 42, in simple_lapack
    a = af.matmulTN(a, a) + 10 * af.identity(5,5)
  File "C:\git\arrayfire-python\arrayfire\blas.py", line 88, in matmulTN
    MATPROP.TRANS.value, MATPROP.NONE.value))
  File "C:\git\arrayfire-python\arrayfire\util.py", line 79, in safe_call
    raise RuntimeError(to_str(err_str))
RuntimeError: In function class std::shared_ptr<float> __cdecl opencl::Array<float>::getMappedPtr(void) const
In file src\backend\opencl\Array.hpp:260
OpenCL Error (-59): Invalid Operation when calling clEnqueueMapBuffer
```

**Comment by rstub** [comment]
Any news on this issue? It still is present using

```
ArrayFire v3.7.0 (OpenCL, 64-bit Linux, build 5e973d01)
-0- BEIGNET: Intel(R) HD Graphics 5500 BroadWell U-Processor GT2, 4096 MB
[1] Intel(R) OpenCL HD Graphics: Intel(R) Gen8 HD Graphics NEO, 9400 MB
-2- POCL: pthread-Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz, 9702 MB
```

**Comment by 9prady9** [comment]
@rstub The commit hash from your info is from a very old commit dated June 14, 2019. We recently made a feature release 3.7.0. Can you please test that out and let us know. You can checkout the tag v3.7.0 if you want to build the project on your own.

**Comment by rstub** [comment]
I had realized that, which is why I asked about building Debian packages on Slack. Anyway, I have now tested with the new version, and the error persists:

```cpp
#include <arrayfire.h>

int main() {
    af::setDevice(1);
    af::info();
    af::array X = af::randn(3, 3);
    af_print(af::matmulTN(X, X));
    return 0;
}
```

yields

```
ArrayFire v3.7.0 (OpenCL, 64-bit Linux, build eed71274)
-0- BEIGNET: Intel(R) HD Graphics 5500 BroadWell U-Processor GT2, 4096 MB
[1] Intel(R) OpenCL HD Graphics: Intel(R) Gen8 HD Graphics NEO, 9400 MB
-2- POCL: pthread-Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz, 9702 MB
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function af_err af_matmul(void**, af_array, af_array, af_mat_prop, af_mat_prop)
In file src/api/c/blas.cpp:253


 0# 0x00007F9B2C12CC0E in /lib/libafopencl.so.3
 1# af_matmul in /lib/libaf.so.3
 2# af::matmulTN(af::array const&, af::array const&) in /lib/libaf.so.3
 3# 0x000055590691D111 in ./square-mat
 4# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
 5# 0x000055590691D17A in ./square-mat

In function af::array af::matmulTN(const af::array&, const af::array&)
In file src/api/cpp/blas.cpp:30
Aborted
``` 

Devices 0 and 2 work without problems.

**Comment by 9prady9** [comment]
@rstub Thank you for testing it out. Can you please re-run the executable with following options.
```
export AF_PRINT_ERRORS=1
export AF_TRACE=all
./program
export AF_PRINT_ERRORS=0 # to turn off
export AF_TRACE="" # to turn off
```

**Comment by rstub** [comment]
Here you are 

```
[unified][1581938315][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:140 ] Attempting: Default System Paths
[unified][1581938315][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:145 ] Found: libafcpu.so.3
[unified][1581938315][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:152 ] Device Count: 1.
[unified][1581938315][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:140 ] Attempting: Default System Paths
[unified][1581938315][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:145 ] Found: libafopencl.so.3
[platform][1581938316][266629] [ /home/ralf/devel/arrayfire/src/backend/common/DependencyModule.cpp:55 ] Attempting to load: libforge.so
[platform][1581938316][266629] [ /home/ralf/devel/arrayfire/src/backend/common/DependencyModule.cpp:60 ] Unable to open forge
[platform][1581938316][266629] [ /home/ralf/devel/arrayfire/src/backend/opencl/device_manager.cpp:204 ] Found 3 OpenCL platforms
[platform][1581938316][266629] [ /home/ralf/devel/arrayfire/src/backend/opencl/device_manager.cpp:215 ] Found 1 devices on platform Intel(R) OpenCL HD Graphics
[platform][1581938316][266629] [ /home/ralf/devel/arrayfire/src/backend/opencl/device_manager.cpp:219 ] Found device Intel(R) Gen8 HD Graphics NEO on platform Intel(R) OpenCL HD Graphics
[platform][1581938316][266629] [ /home/ralf/devel/arrayfire/src/backend/opencl/device_manager.cpp:215 ] Found 1 devices on platform Intel Gen OCL Driver
[platform][1581938316][266629] [ /home/ralf/devel/arrayfire/src/backend/opencl/device_manager.cpp:219 ] Found device Intel(R) HD Graphics 5500 BroadWell U-Processor GT2 on platform Intel Gen OCL Driver
[platform][1581938316][266629] [ /home/ralf/devel/arrayfire/src/backend/opencl/device_manager.cpp:215 ] Found 1 devices on platform Portable Computing Language
[platform][1581938316][266629] [ /home/ralf/devel/arrayfire/src/backend/opencl/device_manager.cpp:219 ] Found device pthread-Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz on platform Portable Computing Language
[platform][1581938316][266629] [ /home/ralf/devel/arrayfire/src/backend/opencl/device_manager.cpp:226 ] Found 3 OpenCL devices
[platform][1581938316][266629] [ /home/ralf/devel/arrayfire/src/backend/opencl/device_manager.cpp:320 ] Default device: 0
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:152 ] Device Count: 3.
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:140 ] Attempting: Default System Paths
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:163 ] Failed to load libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:140 ] Attempting: .
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:163 ] Failed to load ./libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:140 ] Attempting: ./src/backend/cuda
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:163 ] Failed to load ./src/backend/cuda/libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:140 ] Attempting: ../src/backend/cuda
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:163 ] Failed to load ../src/backend/cuda/libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:140 ] Attempting: src/backend/cuda
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:163 ] Failed to load src/backend/cuda/libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:140 ] Attempting: lib
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:163 ] Failed to load lib/libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:140 ] Attempting: lib64
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:163 ] Failed to load lib64/libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:140 ] Attempting: Default System Paths
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:163 ] Failed to load libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:140 ] Attempting: /opt/arrayfire-3/lib/
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:163 ] Failed to load /opt/arrayfire-3/lib//libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:140 ] Attempting: /opt/arrayfire/lib/
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:163 ] Failed to load /opt/arrayfire/lib//libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:140 ] Attempting: /usr/local/lib/
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:163 ] Failed to load /usr/local/lib//libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:140 ] Attempting: /usr/local/arrayfire/lib/
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:163 ] Failed to load /usr/local/arrayfire/lib//libafcuda.so.3: cannot open shared object file: No such file or directory
[unified][1581938316][266629] [ /home/ralf/devel/arrayfire/src/api/unified/symbol_manager.cpp:199 ] AF_DEFAULT_BACKEND: opencl
ArrayFire v3.7.0 (OpenCL, 64-bit Linux, build eed71274)
-0- BEIGNET: Intel(R) HD Graphics 5500 BroadWell U-Processor GT2, 4096 MB
[1] Intel(R) OpenCL HD Graphics: Intel(R) Gen8 HD Graphics NEO, 9400 MB
-2- POCL: pthread-Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz, 9702 MB
[mem][1581938316][266629] [ /home/ralf/devel/arrayfire/src/backend/opencl/memory.cpp:157 ] nativeAlloc: 1 KB 0x5557a4503da0
[mem][1581938316][266629] [ /home/ralf/devel/arrayfire/src/backend/opencl/memory.cpp:157 ] nativeAlloc: 1 KB 0x5557a45f0650
OpenCL Error (-59): Invalid Operation when calling clEnqueueMapBuffer
In function af_err af_matmul(void**, af_array, af_array, af_mat_prop, af_mat_prop)
In file src/api/c/blas.cpp:253


 0# 0x00007FCBF275BC0E in /lib/libafopencl.so.3
 1# af_matmul in /lib/libaf.so.3
 2# af::matmulTN(af::array const&, af::array const&) in /lib/libaf.so.3
 3# 0x00005557A3F78111 in ./square-mat
 4# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
 5# 0x00005557A3F7817A in ./square-mat

terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function af_err af_matmul(void**, af_array, af_array, af_mat_prop, af_mat_prop)
In file src/api/c/blas.cpp:253


 0# 0x00007FCBF275BC0E in /lib/libafopencl.so.3
 1# af_matmul in /lib/libaf.so.3
 2# af::matmulTN(af::array const&, af::array const&) in /lib/libaf.so.3
 3# 0x00005557A3F78111 in ./square-mat
 4# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
 5# 0x00005557A3F7817A in ./square-mat

In function af::array af::matmulTN(const af::array&, const af::array&)
In file src/api/cpp/blas.cpp:30
Aborted
```

**Comment by 9prady9** [comment]
@rstub Thanks once again. The trace looks good until it fails on OpenCL API call `clEnqueueMapBuffer` which is only used in cpu-fallback implementation of gemm(for OpenCL backend). However, that code-path runs only under OSX which makes me think it could be a Intel-OpenCL implementation bug given that same code runs fine on the other two OpenCL implementations(BEIGNET and POCL). I don't have HD graphics setup with me to give a 100% confirmation, but we can keep this issue open. @umar456 Any thoughts ?

**Comment by umar456** [comment]
I am able to reproduce it. I will look at it sometime tomorrow.

**Comment by rstub** [comment]
Thanks. #2774 fixed the issue for me.
