### ISSUE TITLE
SIGSEGV with getDefaultRandomEngine()

### ISSUE THREAD

**Issue by rstub** [arrayfire/arrayfire#2000]
When I try to use getDefaultRandomEngine() I get a SIGSEGV. Example code:

```C++
#include <arrayfire.h>

int main() {
    af::randomEngine engine = af::getDefaultRandomEngine();
    return 0;
}
```

And gdb log:
```
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bad...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/ralf/devel/rcpparrayfire/tmp/bad 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffd8aa3700 (LWP 11019)]
[New Thread 0x7fffd4dec700 (LWP 11020)]
[Thread 0x7fffd4dec700 (LWP 11020) exited]
[New Thread 0x7fffd4dec700 (LWP 11021)]
[New Thread 0x7fffd2501700 (LWP 11031)]
[New Thread 0x7fffd2100700 (LWP 11032)]
[New Thread 0x7fffd1cff700 (LWP 11033)]

Thread 1 "bad" received signal SIGSEGV, Segmentation fault.
0x00007fffdebadb7b in ?? () from /usr/local/lib/libafopencl.so.3
(gdb) backtrace
#0  0x00007fffdebadb7b in ?? () from /usr/local/lib/libafopencl.so.3
#1  0x00007fffdebae480 in af_retain_array () from /usr/local/lib/libafopencl.so.3
#2  0x00007ffff794e1df in ?? () from /usr/local/lib/libaf.so.3
#3  0x00007ffff796adaa in af_retain_array () from /usr/local/lib/libaf.so.3
#4  0x00007fffdee30681 in af_retain_random_engine () from /usr/local/lib/libafopencl.so.3
#5  0x00007ffff794e1df in ?? () from /usr/local/lib/libaf.so.3
#6  0x00007ffff7b21c81 in af::getDefaultRandomEngine() () from /usr/local/lib/libaf.so.3
#7  0x0000555555554965 in main ()
(gdb) 
```

I am using ArrayFire 3.5.1 (installed with the binary installer) on Debian.

**Comment by 9prady9** [comment]
@rstub I was able to reproduce this and I am looking into it.
