### ISSUE TITLE
Tests failing on Tegra TX2 R28.2-DP with AF master-3.6.0 

### ISSUE THREAD

**Issue by HoneyPatouceul** [arrayfire/arrayfire#2036]
Similar to 3.5.1 issue #2001, but on master branch I see 2 tests failing in release mode and one more in Debug or default, as already reported in issue #2028.
Here are some additional details:

**Failure with blas_cuda/MatrixMultiply.Batched:**
```
./test/blas_cuda --gtest_filter=MatrixMultiply.Batched
Running main() from gtest_main.cc
Note: Google Test filter = MatrixMultiply.Batched
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from MatrixMultiply
[ RUN      ] MatrixMultiply.Batched
/media/nvidia/Data/arrayfire/github/arrayfire/test/blas.cpp:267: Failure
Expected: (af::max<float>(af::abs(c_ij - res))) < (1E-5), actual: 0.000488281 vs 1e-05
 for d2 = 2 for d3 = 1
[  FAILED  ] MatrixMultiply.Batched (3371 ms)
[----------] 1 test from MatrixMultiply (3372 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (3372 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] MatrixMultiply.Batched

 1 FAILED TEST
```
**GPU Memory fault (Warp Illegal Address) with canny_cuda/CannyEdgeDetector.OtsuThreshold:**
```
./test/canny_cuda --gtest_filter=CannyEdgeDetector.OtsuThreshold
Running main() from gtest_main.cc
Note: Google Test filter = CannyEdgeDetector.OtsuThreshold
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from CannyEdgeDetector
[ RUN      ] CannyEdgeDetector.OtsuThreshold
In function To cuda::kernel::reduce_all(cuda::CParam<T>, bool, double) [with Ti = float; To = float; af_op_t op = (af_op_t)18u]
In file src/backend/cuda/kernel/reduce.hpp:422
CUDA Error (4): unspecified launch failure

/media/nvidia/Data/arrayfire/github/arrayfire/test/canny.cpp:120: Failure
      Expected: AF_SUCCESS
      Which is: 0
To be equal to: af_canny(&_outArray, inArray, AF_CANNY_THRESHOLD_AUTO_OTSU, 0.08, 0.32, 3, false)
      Which is: 998
[  FAILED  ] CannyEdgeDetector.OtsuThreshold (4170 ms)
[----------] 1 test from CannyEdgeDetector (4170 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (4170 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CannyEdgeDetector.OtsuThreshold

 1 FAILED TEST
```
leading to these kernel messages:
```
[23392.668188] ---- mlocks ----

[23392.672662] ---- syncpts ----
[23392.675747] id 4 (disp_d) min 109733 max 109733 refs 1 (previous client : )
[23392.682793] id 5 (disp_e) min 2 max 2 refs 1 (previous client : )
[23392.688993] id 7 (vblank1) min 553337 max 0 refs 1 (previous client : )
[23392.695708] id 18 (17000000.gp10b_507) min 31007946 max 31007946 refs 1 (previous client : )
[23392.704229] id 19 (17000000.gp10b_506) min 36 max 36 refs 1 (previous client : )
[23392.711722] id 21 (17000000.gp10b_505) min 579998 max 579998 refs 1 (previous client : 17000000.gp10b_505)
[23392.721457] id 22 (17000000.gp10b_504) min 834 max 834 refs 1 (previous client : 17000000.gp10b_504)
[23392.730667] id 23 (17000000.gp10b_503) min 19786 max 19786 refs 1 (previous client : 17000000.gp10b_503)
[23392.740235] id 24 (17000000.gp10b_502) min 227442 max 227444 refs 1 (previous client : 17000000.gp10b_502)
[23392.749974] id 25 (17000000.gp10b_501) min 4200 max 4200 refs 1 (previous client : 17000000.gp10b_501)

[23392.761821] ---- channels ----
[23392.764934] 
               channel 1 - 15820000.se

[23392.771464] NvHost basic channel registers:
[23392.775756] CMDFIFO_STAT_0:  00002040
[23392.779514] CMDFIFO_RDATA_0: 0060c104
[23392.783275] CMDP_OFFSET_0:   00000000
[23392.787032] CMDP_CLASS_0:    00000000
[23392.790785] CHANNELSTAT_0:   00000000
[23392.794532] The CDMA sync queue is empty.

[23392.800136] 
               channel 2 - 15830000.se

[23392.806689] NvHost basic channel registers:
[23392.810947] CMDFIFO_STAT_0:  00002040
[23392.814664] CMDFIFO_RDATA_0: 84800900
[23392.818411] CMDP_OFFSET_0:   00000000
[23392.822157] CMDP_CLASS_0:    00000000
[23392.825893] CHANNELSTAT_0:   00000000
[23392.829581] The CDMA sync queue is empty.

[23392.835235] 
               channel 3 - 15840000.se

[23392.841774] NvHost basic channel registers:
[23392.846029] CMDFIFO_STAT_0:  00002040
[23392.849778] CMDFIFO_RDATA_0: 1000006c
[23392.853449] CMDP_OFFSET_0:   00000000
[23392.857172] CMDP_CLASS_0:    00000000
[23392.860889] CHANNELSTAT_0:   00000000
[23392.864597] The CDMA sync queue is empty.

[23392.870197] 
               ---- host general irq ----

[23392.876928] sync_intc0mask = 0x00000001
[23392.880798] sync_intmask = 0x50000003
[23392.884495] 
               ---- host syncpt irq mask ----

[23392.891572] 
               ---- host syncpt irq status ----

[23392.898804] syncpt_thresh_cpu0_int_status(0) = 0x00000000
[23392.904226] syncpt_thresh_cpu0_int_status(1) = 0x00000000
[23392.909643] syncpt_thresh_cpu0_int_status(2) = 0x00000000
[23392.915049] syncpt_thresh_cpu0_int_status(3) = 0x00000000
[23392.920457] syncpt_thresh_cpu0_int_status(4) = 0x00000000
[23392.925860] syncpt_thresh_cpu0_int_status(5) = 0x00000000
[23392.931265] syncpt_thresh_cpu0_int_status(6) = 0x00000000
[23392.936673] syncpt_thresh_cpu0_int_status(7) = 0x00000000
[23392.942077] syncpt_thresh_cpu0_int_status(8) = 0x00000000
[23392.947483] syncpt_thresh_cpu0_int_status(9) = 0x00000000
[23392.952887] syncpt_thresh_cpu0_int_status(10) = 0x00000000
[23392.958377] syncpt_thresh_cpu0_int_status(11) = 0x00000000
[23392.963863] syncpt_thresh_cpu0_int_status(12) = 0x00000000
[23392.969358] syncpt_thresh_cpu0_int_status(13) = 0x00000000
[23392.974846] syncpt_thresh_cpu0_int_status(14) = 0x00000000
[23392.980334] syncpt_thresh_cpu0_int_status(15) = 0x00000000
[23392.985825] syncpt_thresh_cpu0_int_status(16) = 0x00000000
[23392.991353] syncpt_thresh_cpu0_int_status(17) = 0x00000000
[23392.996893] 17000000.gp10b pbdma 0: 
[23393.000350] id: 3 (tsg), next_id: 3 (tsg) chan status: invalid
[23393.006402] PUT: 0000001f08300078 GET: 0000001f08300060 FETCH: 0000000b HEADER: 20011b08

[23393.016050] 17000000.gp10b eng 0: 
[23393.019331] id: 3 (tsg), next_id: 3 (tsg), ctx status: valid 
[23393.025102] faulted 
[23393.025860] busy 

[23393.029295] 17000000.gp10b eng 1: 
[23393.032570] id: 4 (tsg), next_id: 4 (tsg), ctx status: valid 


[23393.041618] 500-17000000.gp10b, pid 6307, refs: 2: 
[23393.046377] channel status:  in use pending_acquire busy
[23393.051907] RAMFC : TOP: 800000010066b7f8 PUT: 000000010066b858 GET: 000000010066b7f8 FETCH: 0000c4010066b7f8
               HEADER: 20040718 COUNT: 01110002
               SYNCPOINT 00000000 00000000 SEMAPHORE 00000001 00017fcc 00000002 00081004

[23393.075422] 501-17000000.gp10b, pid 6307, refs: 2: 
[23393.080158] channel status:  in use idle not busy
[23393.085079] RAMFC : TOP: 8000000100530294 PUT: 0000000100530294 GET: 0000000100530294 FETCH: 0000000100530294
               HEADER: 60400000 COUNT: 80000000
               SYNCPOINT 00000000 00000000 SEMAPHORE 00000000 00000000 00000000 00000000

[23393.108595] 502-17000000.gp10b, pid 6307, refs: 4: 
[23393.113334] channel status:  in use on_eng_pending busy
[23393.118773] RAMFC : TOP: 8000001f08300060 PUT: 0000001f08300078 GET: 0000001f08300060 FETCH: 0000001f08300078
               HEADER: 20011b08 COUNT: a0110002
               SYNCPOINT 00000000 00001801 SEMAPHORE 00000001 0000fba0 0000053a 00081004

[23393.142330] 503-17000000.gp10b, pid 6307, refs: 2: 
[23393.147069] channel status:  in use pending busy
[23393.151900] RAMFC : TOP: 8000000100312d30 PUT: 00000001003130e4 GET: 0000000100312d30 FETCH: 00076c0100312d30
               HEADER: 20010180 COUNT: 01110002
               SYNCPOINT 00000000 00001701 SEMAPHORE 00000001 00017fd4 00000002 00080004

[23393.175420] 504-17000000.gp10b, pid 6307, refs: 2: 
[23393.180155] channel status:  in use idle not busy
[23393.185074] RAMFC : TOP: 800000010021b9e0 PUT: 000000010021b9e0 GET: 000000010021b9e0 FETCH: 000000010021b9e0
               HEADER: 60400000 COUNT: 80000000
               SYNCPOINT 00000000 00000000 SEMAPHORE 00000001 0000fba0 00000481 00001004

[23393.208594] 505-17000000.gp10b, pid 2146, refs: 6: 
[23393.213332] channel status:  in use pending busy
[23393.218164] RAMFC : TOP: 8000001f08006150 PUT: 0000001f08006150 GET: 0000001f08006150 FETCH: 0000001f08006150
               HEADER: 60400000 COUNT: 80000000
               SYNCPOINT 00000000 00001501 SEMAPHORE 0000001e 029500e0 00000001 00001001

[23393.241722] 506-17000000.gp10b, pid 1194, refs: 2: 
[23393.246460] channel status:  in use idle not busy
[23393.251379] RAMFC : TOP: 8000001f081401b0 PUT: 0000001f081401b0 GET: 0000001f081401b0 FETCH: 0000001f081401b0
               HEADER: 60400000 COUNT: 80000000
               SYNCPOINT 00000000 00001301 SEMAPHORE 00000000 00000000 00000000 00000000

[23393.274930] 507-17000000.gp10b, pid 1194, refs: 52: 
[23393.279751] channel status:  in use pending busy
[23393.284586] RAMFC : TOP: 8000001f08024ca0 PUT: 0000001f08024ca0 GET: 0000001f08024ca0 FETCH: 0000001f08024ca0
               HEADER: 60400000 COUNT: 80000000
               SYNCPOINT 00000000 00001201 SEMAPHORE 0000000d fc001000 0c801ba8 01100002

[23393.308225] 508-17000000.gp10b, pid 1222, refs: 2: 
[23393.312994] channel status:  in use idle not busy
[23393.317920] RAMFC : TOP: 0000000000000000 PUT: 0000000000000000 GET: 0000000000000000 FETCH: 0000000000000000
               HEADER: 60400000 COUNT: 00000000
               SYNCPOINT 00000000 00000000 SEMAPHORE 00000000 00000000 00000000 00000000

[23393.341432] 509-17000000.gp10b, pid 1222, refs: 2: 
[23393.346177] channel status:  in use idle not busy
[23393.351108] RAMFC : TOP: 0000000000000000 PUT: 0000000000000000 GET: 0000000000000000 FETCH: 0000000000000000
               HEADER: 60400000 COUNT: 00000000
               SYNCPOINT 00000000 00000000 SEMAPHORE 00000000 00000000 00000000 00000000

[23393.374663] 510-17000000.gp10b, pid 1222, refs: 2: 
[23393.379401] channel status:  in use idle not busy
[23393.384320] RAMFC : TOP: 0000000000000000 PUT: 0000000000000000 GET: 0000000000000000 FETCH: 0000000000000000
               HEADER: 60400000 COUNT: 00000000
               SYNCPOINT 00000000 00000000 SEMAPHORE 00000000 00000000 00000000 00000000

[23393.407840] 511-17000000.gp10b, pid 1222, refs: 2: 
[23393.412577] channel status:  in use idle not busy
[23393.417493] RAMFC : TOP: 0000000000000000 PUT: 0000000000000000 GET: 0000000000000000 FETCH: 0000000000000000
               HEADER: 60400000 COUNT: 00000000
               SYNCPOINT 00000000 00000000 SEMAPHORE 00000000 00000000 00000000 00000000

[23393.441040] gk20a 17000000.gp10b: gk20a_fifo_handle_mmu_fault:  mmu fault on engine 0, engine subid 0 (gpc), client 10 (t1 3), addr 0x0000000f:0xc2c15000, type 2 (pte), info 0x00000a02,inst_ptr 0xc174c000
               
[23393.466695] gk20a 17000000.gp10b: gk20a_fifo_set_ctx_mmu_error_tsg: TSG 3 generated a mmu fault
[23393.475403] gk20a 17000000.gp10b: gk20a_set_error_notifier_locked: error notifier set to 31 for ch 504
[23393.484800] gk20a 17000000.gp10b: fifo_error_isr: channel reset initiated from fifo_error_isr; intr=0x10000000
```
**Here are traces from debug build with cuda-gdb:**

```
cuda-gdb ./test/canny_cuda
NVIDIA (R) CUDA Debugger
9.0 release
Portions Copyright (C) 2007-2017 NVIDIA Corporation
GNU gdb (GDB) 7.12
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-elf-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./test/canny_cuda...done.
(cuda-gdb) set args  --gtest_filter=CannyEdgeDetector.OtsuThreshold
(cuda-gdb) run
Starting program: /media/nvidia/Data/arrayfire/github/build/TX2-R28.2-DP_Debug/test/canny_cuda --gtest_filter=CannyEdgeDetector.OtsuThreshold
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
Running main() from gtest_main.cc
Note: Google Test filter = CannyEdgeDetector.OtsuThreshold
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from CannyEdgeDetector
[ RUN      ] CannyEdgeDetector.OtsuThreshold
[New Thread 0x7f93a29240 (LWP 6391)]

CUDA Exception: Warp Illegal Address

Thread 1 "canny_cuda" received signal CUDA_EXCEPTION_14, Warp Illegal Address.
[Switching focus to CUDA kernel 0, grid 8, block (1,53,0), thread (0,10,0), device 0, sm 0, warp 55, lane 0]
0x0000000012ab57d0 in void cuda::kernel::nonMaxSuppressionKernel<float>(cuda::Param<float>, cuda::CParam<float>, cuda::CParam<float>, cuda::CParam<float>, unsigned int, unsigned int)<<<(80,54,1),(16,16,1)>>> ()
(cuda-gdb) bt
#0  0x0000000012ab57d0 in void cuda::kernel::nonMaxSuppressionKernel<float>(cuda::Param<float>, cuda::CParam<float>, cuda::CParam<float>, cuda::CParam<float>, unsigned int, unsigned int)<<<(80,54,1),(16,16,1)>>> ()
(cuda-gdb) 
#0  0x0000000012ab57d0 in void cuda::kernel::nonMaxSuppressionKernel<float>(cuda::Param<float>, cuda::CParam<float>, cuda::CParam<float>, cuda::CParam<float>, unsigned int, unsigned int)<<<(80,54,1),(16,16,1)>>> ()
```

Last, jit_cuda/JIT.ISSUE_1646 fails in debug mode, related to issue #2028, waiting for NVIDIA advices.

Let me know if I may help.

**Comment by 9prady9** [comment]
Canny test failure is being tracked in #2001

**Comment by HoneyPatouceul** [comment]
@9prady9 
I don't want to bother you, but I still get the blas_cuda test failing on my TX1-R28.1 (cuda8) and on my TX2-R28.2-DP (cuda9).

On TX1-R28.1, canny_cuda OtsuThreshold test passes, but using  dmesg --follow I see it triggers memory errors:
```
[ 4527.378399] smmu_dump_pagetable(): No valid page table
[ 4527.383651] mc-err: (30) csr_gpusrd2: EMEM decode error on PDE or PTE entry
[ 4527.390655] mc-err:   status = 0x60000088; addr = 0x1b92b800
[ 4527.396336] mc-err:   secure: no, access-type: read, SMMU fault: nr-nw-s
[ 4527.403201] smmu_dump_pagetable(): No valid page table
[ 4527.408358] mc-err: (30) csr_gpusrd2: EMEM decode error on PDE or PTE entry
[ 4527.415326] mc-err:   status = 0x60000088; addr = 0x1b92b800
[ 4527.420990] mc-err:   secure: no, access-type: read, SMMU fault: nr-nw-s
[ 4527.427731] smmu_dump_pagetable(): No valid page table
[ 4527.432877] mc-err: (30) csr_gpusrd2: EMEM decode error on PDE or PTE entry
[ 4527.439838] mc-err:   status = 0x60000088; addr = 0x1b92b800
[ 4527.445494] mc-err:   secure: no, access-type: read, SMMU fault: nr-nw-s
[ 4527.452216] smmu_dump_pagetable(): No valid page table
[ 4527.457358] mc-err: (30) csr_gpusrd2: EMEM decode error on PDE or PTE entry
[ 4527.464314] mc-err:   status = 0x60000088; addr = 0x1b92b800
[ 4527.469970] mc-err:   secure: no, access-type: read, SMMU fault: nr-nw-s
[ 4527.476685] mc-err: Too many MC errors; throttling prints
```
Are you testing on a tegra or another arm64 platform ?
If you did it on TX1-R28.1 or TX2-R28.2-DP, probably the problem is on my side. In such case would you please send me your arrayfire build CMakeCache.txt for checking any config difference ?

Thanks

**Comment by 9prady9** [comment]
I tested it on a tegra, thats the only arm64 platform we test on our servers. It is TX2 that I am testing on.
```
Device 0: "GP10B"
  CUDA Driver Version / Runtime Version          8.5 / 8.0
  CUDA Capability Major/Minor version number:    6.2
```
on `R27` release. Is it still failing with the same error as earlier ?

**Comment by 9prady9** [comment]
@HoneyPatouceul 
[CMakeCache.txt](https://github.com/arrayfire/arrayfire/files/1614956/CMakeCache.txt)
Here is the cmake cache on my local build.

**Comment by HoneyPatouceul** [comment]
Thanks.

It may be related to cuda versions.

I've had my TX2 using R27.0.1 (was a pre-realease) with cuda8.0.64-1.
Then I've updated to R28.1 with cuda8.0.84 and got some new problems with jit.
Recently I've upgraded to R28.2-DP (developer preview) with cuda9.0.252 and got new problems.

I have atlas installed while in your case open_blas is used. I'll try to check if it has some relation for blas_cuda failure.
Also noticed that CUDA_NPPI_LIBRARY is not found on my TX2. I think this may be related to the library being split in several flavors in cuda9.

Last, I'm using cmake-gui, and some cmake variables are set as OFF by cmake-gui while they're set to NO in your case. I'll try to investigate further.

**Comment by HoneyPatouceul** [comment]
@9prady9 
Well, so far I still consider these errors to be active issues on recent L4T versions.
I've tried to build from your config, just translating paths and cuda9 options for ruling out any cmake-gui issue, but still get the same.
Removing atlas doesn't change the blas_cuda issue.
I've built a version on my TX1 using R28.1 that was passing the blas_cuda test, but unsure how I did it (unable to reproduce, but I remember it took ages to build and was running slow).
Furthermore, I notice your CMakeCache.txt ends with : 
```
//Result of TRY_RUN
run_result:INTERNAL=255
```
while mines end with result 0.

I expect L4T R28.2.1 to be soon released. I would suggest you to upgrade and do more testing with it (you may also try R28.1 from now).

**Comment by 9prady9** [comment]
I will try to upgrade to L4T `28.1` and check for any failed tests on our tegra.
