### ISSUE TITLE
AF 3.6.0 crash with nvidia driver 396

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2158]
Upgraded a centOS 6 machine with latest 396 drivers and latest kernel 
$ uname -a
Linux gitbuild101 2.6.32-696.28.1.el6.x86_64 #1 SMP Wed May 9 23:09:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ nvidia-smi 
Fri May 18 12:38:49 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.26                 Driver Version: 396.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:02:00.0 Off |                  N/A |
| 27%   35C    P0    38W / 180W |      0MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN V             Off  | 00000000:03:00.0 Off |                  N/A |
| 28%   42C    P0    38W / 250W |      0MiB / 12066MiB |      3%      Default |

and examples/benchmark/blas_cuda 
from 
http://arrayfire.s3.amazonaws.com/3.6.0/ArrayFire-no-gl-v3.6.0_Linux_x86_84.sh
crashs at static init so no info :
 
(gdb) bt
#0  0x0000003c55232495 in raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x0000003c55233c75 in abort () at abort.c:92
#2  0x0000003c5720dbbd in _Unwind_SetGR (context=<value optimized out>, index=<value optimized out>, val=<value optimized out>) at ../../../gcc/unwind-dw2.c:247
#3  0x0000003c57212c3d in __gcc_personality_v0 (version=<value optimized out>, actions=<value optimized out>, exception_class=<value optimized out>, ue_header=0x9bdcb0, context=0x7fffffffd340) at ../../../gcc/unwind-c.c:228
#4  0x00007fffb9dcf3d3 in _Unwind_RaiseException_Phase2 () from /local/wtambellini/arrayfire-no-gl-3.6.0/lib/libafcuda.so.3
#5  0x00007fffb9dcfc27 in _Unwind_Resume () from /local/wtambellini/arrayfire-no-gl-3.6.0/lib/libafcuda.so.3
#6  0x00007fffb8c4978e in cuda::getDeviceInfo() () from /local/wtambellini/arrayfire-no-gl-3.6.0/lib/libafcuda.so.3
#7  0x00007fffb8d733ee in void std::__once_call_impl<std::_Bind_simple<af_init::{lambda()#1} ()()> >() () from /local/wtambellini/arrayfire-no-gl-3.6.0/lib/libafcuda.so.3
#8  0x0000003c5560ce03 in pthread_once () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_once.S:104
#9  0x00007fffb8d73a60 in af_init () from /local/wtambellini/arrayfire-no-gl-3.6.0/lib/libafcuda.so.3
#10 0x00007fffb8c744b1 in af_create_handle () from /local/wtambellini/arrayfire-no-gl-3.6.0/lib/libafcuda.so.3
#11 0x00007fffb8fe5ea2 in af::initEmptyArray(void**, af_dtype, long long, long long, long long, long long) () from /local/wtambellini/arrayfire-no-gl-3.6.0/lib/libafcuda.so.3
#12 0x0000000000401236 in __static_initialization_and_destruction_0(int, int) ()
#13 0x0000000000401262 in global constructors keyed to main ()
#14 0x0000000000401336 in __do_global_ctors_aux ()
#15 0x0000000000400d4b in _init ()
#16 0x00000079009a9820 in ?? ()
#17 0x00000000004012c5 in __libc_csu_init ()
#18 0x0000003c5521ecb0 in __libc_start_main (main=0x401012 <main>, argc=1, ubp_av=0x7fffffffe5c8, init=0x401280 <__libc_csu_init>, fini=<value optimized out>, rtld_fini=<value optimized out>, stack_end=0x7fffffffe5b8)
    at libc-start.c:185
#19 0x0000000000400ee9 in _start ()

**Comment by WilliamTambellini** [comment]
Reverting to 390 does fix that. 
This ticket could be closed.
