### ISSUE TITLE
Crash in spdlog::synchronous_factory::create

### ISSUE THREAD

**Issue by WilliamTambellini** [arrayfire/arrayfire#2536]
Hi,
Here is a crash seen on CentOS7 at exit time with my software using AF 3.6.4 : 

Program terminated with signal 11, Segmentation fault.
#0  0x00007ff474008c98 in ?? ()
(gdb) bt
#0  0x00007ff474008c98 in ?? ()
#1  0x00007ff494804a58 in std::shared_ptr<spdlog::logger> spdlog::synchronous_factory::create<spdlog::sinks::stdout_sink<spdlog::details::console_stdout, spdlog::details::console_mutex>>(std::string) () from lib/libaf.so.3
#2  0x00007ff4948029ac in common::loggerFactory(std::string) () from lib/libaf.so.3
#3  0x00007ff4947e8d2e in unified::AFSymbolManager::AFSymbolManager() () from lib/libaf.so.3
#4  0x00007ff4947e8e9e in unified::AFSymbolManager::getInstance() () from lib/libaf.so.3
#5  0x00007ff4947720c8 in af_sync () from lib/libaf.so.3
#6  0x00007ff49489e312 in af::sync(int) () from lib/libaf.so.3

Perhaps not easy to reproduce with a simple AF example, probably related to threading but to be confirmed.
W.

**Comment by WilliamTambellini** [comment]
Probably fixed in 3.7.0
