### ISSUE TITLE
[Build] git version of arrayfire; reduce_cuda.exe generates 77 failed tests

### ISSUE THREAD

**Issue by 3togo** [arrayfire/arrayfire#3339]
compile git version of arrayfire using visual studio 2022 & cuda 11.8 .  

Description
===========

reduce_cuda.exe generates  77 failed test when running GTX1060. No failed when running GTX 3080

Error Log
---------

```
[----------] Global test environment tear-down
[==========] 765 tests from 26 test suites ran. (37228 ms total)
[  PASSED  ] 688 tests.
[  FAILED  ] 77 tests, listed below:
[  FAILED  ] Reduce/0.Test_sum, where TypeParam = float
[  FAILED  ] Reduce/0.Test_min, where TypeParam = float
[  FAILED  ] Reduce/0.Test_max, where TypeParam = float
[  FAILED  ] Reduce/0.Test_any_true, where TypeParam = float
[  FAILED  ] Reduce/0.Test_all_true, where TypeParam = float
[  FAILED  ] Reduce/0.Test_count, where TypeParam = float
[  FAILED  ] Reduce/1.Test_sum, where TypeParam = double
[  FAILED  ] Reduce/1.Test_min, where TypeParam = double
[  FAILED  ] Reduce/1.Test_max, where TypeParam = double
[  FAILED  ] Reduce/1.Test_any_true, where TypeParam = double
[  FAILED  ] Reduce/1.Test_all_true, where TypeParam = double
[  FAILED  ] Reduce/1.Test_count, where TypeParam = double
[  FAILED  ] Reduce/2.Test_sum, where TypeParam = struct af::af_cfloat
[  FAILED  ] Reduce/2.Test_min, where TypeParam = struct af::af_cfloat
[  FAILED  ] Reduce/2.Test_max, where TypeParam = struct af::af_cfloat
[  FAILED  ] Reduce/2.Test_any_true, where TypeParam = struct af::af_cfloat
[  FAILED  ] Reduce/2.Test_all_true, where TypeParam = struct af::af_cfloat
[  FAILED  ] Reduce/2.Test_count, where TypeParam = struct af::af_cfloat
[  FAILED  ] Reduce/3.Test_sum, where TypeParam = struct af::af_cdouble
[  FAILED  ] Reduce/3.Test_min, where TypeParam = struct af::af_cdouble
[  FAILED  ] Reduce/3.Test_max, where TypeParam = struct af::af_cdouble
[  FAILED  ] Reduce/3.Test_any_true, where TypeParam = struct af::af_cdouble
[  FAILED  ] Reduce/3.Test_all_true, where TypeParam = struct af::af_cdouble
[  FAILED  ] Reduce/3.Test_count, where TypeParam = struct af::af_cdouble
[  FAILED  ] Reduce/4.Test_sum, where TypeParam = unsigned int
[  FAILED  ] Reduce/4.Test_min, where TypeParam = unsigned int
[  FAILED  ] Reduce/4.Test_max, where TypeParam = unsigned int
[  FAILED  ] Reduce/4.Test_any_true, where TypeParam = unsigned int
[  FAILED  ] Reduce/4.Test_all_true, where TypeParam = unsigned int
[  FAILED  ] Reduce/4.Test_count, where TypeParam = unsigned int
[  FAILED  ] Reduce/5.Test_sum, where TypeParam = int
[  FAILED  ] Reduce/5.Test_min, where TypeParam = int
[  FAILED  ] Reduce/5.Test_max, where TypeParam = int
[  FAILED  ] Reduce/5.Test_any_true, where TypeParam = int
[  FAILED  ] Reduce/5.Test_all_true, where TypeParam = int
[  FAILED  ] Reduce/5.Test_count, where TypeParam = int
[  FAILED  ] Reduce/6.Test_sum, where TypeParam = __int64
[  FAILED  ] Reduce/6.Test_min, where TypeParam = __int64
[  FAILED  ] Reduce/6.Test_max, where TypeParam = __int64
[  FAILED  ] Reduce/6.Test_any_true, where TypeParam = __int64
[  FAILED  ] Reduce/6.Test_all_true, where TypeParam = __int64
[  FAILED  ] Reduce/6.Test_count, where TypeParam = __int64
[  FAILED  ] Reduce/7.Test_sum, where TypeParam = unsigned __int64
[  FAILED  ] Reduce/7.Test_min, where TypeParam = unsigned __int64
[  FAILED  ] Reduce/7.Test_max, where TypeParam = unsigned __int64
[  FAILED  ] Reduce/7.Test_any_true, where TypeParam = unsigned __int64
[  FAILED  ] Reduce/7.Test_all_true, where TypeParam = unsigned __int64
[  FAILED  ] Reduce/7.Test_count, where TypeParam = unsigned __int64
[  FAILED  ] Reduce/8.Test_sum, where TypeParam = unsigned char
[  FAILED  ] Reduce/8.Test_min, where TypeParam = unsigned char
[  FAILED  ] Reduce/8.Test_max, where TypeParam = unsigned char
[  FAILED  ] Reduce/8.Test_any_true, where TypeParam = unsigned char
[  FAILED  ] Reduce/8.Test_all_true, where TypeParam = unsigned char
[  FAILED  ] Reduce/8.Test_count, where TypeParam = unsigned char
[  FAILED  ] Reduce/9.Test_sum, where TypeParam = short
[  FAILED  ] Reduce/9.Test_min, where TypeParam = short
[  FAILED  ] Reduce/9.Test_max, where TypeParam = short
[  FAILED  ] Reduce/9.Test_any_true, where TypeParam = short
[  FAILED  ] Reduce/9.Test_all_true, where TypeParam = short
[  FAILED  ] Reduce/9.Test_count, where TypeParam = short
[  FAILED  ] Reduce/10.Test_sum, where TypeParam = unsigned short
[  FAILED  ] Reduce/10.Test_min, where TypeParam = unsigned short
[  FAILED  ] Reduce/10.Test_max, where TypeParam = unsigned short
[  FAILED  ] Reduce/10.Test_any_true, where TypeParam = unsigned short
[  FAILED  ] Reduce/10.Test_all_true, where TypeParam = unsigned short
[  FAILED  ] Reduce/10.Test_count, where TypeParam = unsigned short
[  FAILED  ] Reduce.Test_Reduce_Big0
[  FAILED  ] Reduce.Test_sum_CPP
[  FAILED  ] Reduce.Test_min_CPP
[  FAILED  ] Reduce.Test_max_CPP
[  FAILED  ] Reduce.Test_anyTrue_CPP
[  FAILED  ] Reduce.Test_allTrue_CPP
[  FAILED  ] Reduce.Test_count_CPP
[  FAILED  ] ReduceByKey.MultiBlockReduceContig10
[  FAILED  ] ReduceByKey.MultiBlockReduceRandom10
[  FAILED  ] ReduceByKey.MultiBlockReduceContig500
[  FAILED  ] ReduceByKey.MultiBlockReduceByKeyRandom500

77 FAILED TESTS

```

Build Environment
-----------------
Compiler version:  MSVC v170
Operating system: Windows 10

**Comment by 3togo** [comment]
test code:

```
#include <arrayfire.h>
#include <iostream>

int main(int argc, char** argv) {
    af::info();
    int h_A[] = {1, 2, 4, -1, 2, 0, 4, 2, 3};
    af::array a   = af::array(3, 3, h_A);
    af_print(a);
    af::array b = af::max<af::array>(a);
    af_print(b);
    int c = af::max<int>(b);
    std::cout << "c=" << c<< std::endl;
}
```

Using GTX 3080, there is no error.
Using GTX 1060 and cuda 11.8, it will crash.
```

(gdb) bt -10
#1  0x00007ffec77966c0 in _CxxThrowException () from C:\WINDOWS\SYSTEM32\vcruntime140.dll
#2  0x00007ffe4d0d8bae in afcuda!??$max@Varray@af@@@af@@YA?AVarray@0@AEBV10@@Z ()
   from C:\Program Files\AF_dlls\lib\afcuda.dll
#3  0x00007ff657ef15f0 in ?? ()
#4  0x00007ff657ef2839 in ?? ()
#5  0x00007ff657ef26de in ?? ()
#6  0x00007ff657ef259e in ?? ()
#7  0x00007ff657ef28ce in ?? ()
#8  0x00007ffee6c974b4 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\System32\kernel32.dll
#9  0x00007ffee70426a1 in ntdll!RtlUserThreadStart () from C:\WINDOWS\SYSTEM32\ntdll.dll
#10 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)

```

**Comment by 3togo** [comment]
compile in debug mode, could avoid this problem
